import type { Metadata } from 'next'
import { Titillium_Web, Barlow_Semi_Condensed } from 'next/font/google'
import './globals.css'

const titilliumWeb = Titillium_Web({
  weight: ['200', '300', '400', '600', '700', '900'],
  subsets: ['latin'],
  variable: '--font-titillium-web',
})
const barlowSemiCondensed = Barlow_Semi_Condensed({
  weight: ['200', '300', '400', '600', '700', '900'],
  subsets: ['latin'],
  variable: '--font-barlow-semi-condensed',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={
          barlowSemiCondensed.className +
          ' ' +
          titilliumWeb.variable +
          ' ' +
          barlowSemiCondensed.variable
        }
      >
        {children}
      </body>
    </html>
  )
}
