import Link from 'next/link'
import React from 'react'

const TermsOfService = () => {
  return (
    <>
      <div className="text-center my-6 mx-auto px-4 lg:px-0 py-32">
        <div className="mb-1 text-sm font-bold uppercase tracking-wider text-muted-foreground">
          Legal
        </div>
        <h2 className="mb-4 text-4xl font-titillium font-bold text-black dark:text-white">
          Terms of Service
        </h2>
        <div className="mb-3 mx-auto h-1.5 w-12 rounded-lg bg-accent" />
      </div>
      <div className="my-16 prose prose-indigo mx-auto px-6 lg:px-0">
        <div className="space-y-2 mb-6">
          <h2 className="font-bold text-xl">Introduction</h2>
          <p className="text-stone-500 text-base">
            By using our Titan Alloys LLC metal trading services, you agree to
            receive communications from us, including but not limited to emails,
            notifications, and other messages.
          </p>
        </div>

        <div className="space-y-2 mb-6">
          <h2 className="font-bold text-xl">Features:</h2>
          <p className="text-stone-500 text-base">
            Our Titan Alloys LLC metal trading services are constantly evolving
            and improving. We reserve the right to add, remove, or modify
            features at any time without notice.
          </p>
        </div>

        <div className="space-y-2 mb-6">
          <h2>Prohibited Use for Illegal Means:</h2>
          <p className="text-stone-500 text-base">
            Our Titan Alloys LLC metal trading services may only be used for
            lawful purposes. You agree not to use our metal trading services for
            any illegal or unauthorized purpose, including but not limited to
            committing fraud or engaging in illegal activities.
          </p>
        </div>

        <div className="space-y-2 mb-6">
          <h2>Copyright Policy:</h2>
          <p className="text-stone-500 text-base">
            You retain the rights to any content that you generate using our
            Titan Alloys LLC metal trading services. You may use, reproduce,
            distribute, or otherwise exploit the content generated by our metal
            trading services for any lawful purpose, subject to our terms and
            conditions. Any unauthorized use of our metal trading services or
            its content may violate copyright laws, trademark laws, and other
            applicable laws.
          </p>
        </div>

        <div className="space-y-2 mb-6">
          <h2>Contact Us</h2>
          <p className="text-stone-500 text-base">
            If you have any questions or concerns about our policies or the way
            we handle your personal information, please contact us at{' '}
            <Link href="mailto:orders@titanalloysllc.com">
              orders@titanalloysllc.com
            </Link>
          </p>
        </div>
      </div>
    </>
  )
}

export default TermsOfService
